apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: steamgetter
  template:
    metadata:
      labels:
        app: steamgetter
    spec:
      containers:
        - name: steamgetter
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_0a23d47bd49e
          imagePullPolicy: Always
